# Generated by Django 5.2.8 on 2025-11-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_multa', models.CharField(max_length=50, unique=True)),
                ('placa', models.CharField(max_length=15)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('conductor', models.CharField(max_length=120)),
                ('infraccion', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
