# Generated by Django 5.2.8 on 2025-11-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='conductor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='numero_multa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
