# Generated by Django 5.2.8 on 2025-11-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multaApp', '0002_alter_multa_codigo_alter_multa_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='numero_multa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
