# Generated by Django 5.2.8 on 2025-11-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multaApp', '0003_alter_multa_numero_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='numero_multa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
