# Generated by Django 5.2.8 on 2025-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multaApp', '0004_alter_multa_numero_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
