# Generated by Django 5.2.8 on 2025-11-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multaApp', '0006_multa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='conductor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='multa',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='multa',
            name='numero_multa',
            field=models.CharField(blank=True, default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multa',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
